### ISSUE TITLE
Problem with 2y type hash bcrypt 

### ISSUE THREAD

**Issue by dgfmdrv** [chriswebb/csBCrypt#2]
Hello, I'm starting with csBCrypt to create hashs using pre-generated salt (read from api rest, wsse).

I have a problem with hash like this:
   **$2y$**09$WTSOX59Dqr/Xo5DF/yPfUuSuARsNVlQYENiVBbAKlW/UrDUL.Z772

Symfony2 encoder use this type of hash instead of $2a. csBCrypt generate an Exception:
    Additional information: Invalid salt revision

I have been reading and seemed that 2y and 2a is ¿compatible? ¿equal? (don't know). This works:
    hashed = BCrypt.CreateHash(passwd, salt.Replace(@"$2y$", @"$2a$")).Replace(@"$2a$", @"$2y$");

Do you have any cloud about 2y code in a bcrypt hash??
Thanks chriswebb

**Comment by chriswebb** [comment]
Hey there,

It seems as if the 2y revision is a php only revision and was added due to php's crypt_blowfish having a bug with the 2a revision. They created their own 2x and 2y revisions to differentiate between the bugged version of 2a and the non-bugged version respectively.  Meaning 2x is the representation of 2a in crypt_blowfish before the fix, and 2y is the 2a revision after the fix.  

These revision numbers are unfortunately specific to PHP's crypt_blowfish and are not universal standard revision numbers.  For all intents and purposes the 2y version built by php is interchangable with 2a version in languages other than php.  This means that your workaround is the standard solution for exchanging bcrypt hashes between php and other languages.  

If I were to write code to address this, I would add another overload of the CreateHash function to accept a boolean on whether or not the php revision number should be supported.   I would not want to add this support under the standard hash creation function due to the fact that this revision is not a universal standard.

Does this sound like an acceptable solution?

Thanks,
Chris
